/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: scripts/generate-sources.js
 * Run: npm generate:blocks
 * 
 * Source of truth: app/src/app/blocks
 */

export const authLoginSource = `import { Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideMail, lucideLock, lucideEye, lucideEyeOff } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmLabelImports } from '@spartan-ng/helm/label';
import { HlmCardImports } from '@spartan-ng/helm/card';
import { HlmCheckboxImports } from '@spartan-ng/helm/checkbox';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmInputGroupImports } from '@spartan-ng/helm/input-group';

@Component({
  selector: 'app-auth-login-block',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    NgIcon,
    HlmIcon,
    HlmButtonImports,
    HlmInputImports,
    HlmLabelImports,
    HlmCardImports,
    HlmCheckboxImports,
    HlmInputGroupImports,
  ],
  viewProviders: [provideIcons({ lucideMail, lucideLock, lucideEye, lucideEyeOff })],
  template: \`
    <div class="flex h-full items-center justify-center bg-gradient-to-br from-background to-muted/50">
      <section hlmCard class="w-full max-w-md shadow-lg">
        <div hlmCardHeader class="text-center">
          <h2 hlmCardTitle class="text-2xl">Welcome back</h2>
          <p hlmCardDescription>Enter your credentials to access your account</p>
        </div>
        <form [formGroup]="loginForm" hlmCardContent class="space-y-4">
          <div class="space-y-2">
            <label hlmLabel for="login-email">Email</label>
            <div hlmInputGroup>
              <div hlmInputGroupAddon>
                <ng-icon hlm name="lucideMail" size="sm" />
              </div>
              <input
                hlmInputGroupInput
                id="login-email"
                type="email"
                formControlName="email"
                placeholder="name@example.com"
              />
            </div>
          </div>
          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <label hlmLabel for="login-password">Password</label>
              <a href="#" class="text-sm text-primary hover:underline">Forgot password?</a>
            </div>
            <div hlmInputGroup>
              <div hlmInputGroupAddon>
                <ng-icon hlm name="lucideLock" size="sm" />
              </div>
              <input
                hlmInputGroupInput
                id="login-password"
                [type]="showPassword() ? 'text' : 'password'"
                formControlName="password"
                placeholder="Enter your password"
              />
              <div hlmInputGroupAddon align="inline-end">
                <button
                  type="button"
                  hlmInputGroupButton
                  variant="ghost"
                  size="icon-sm"
                  (click)="showPassword.set(!showPassword())"
                >
                  <ng-icon hlm [name]="showPassword() ? 'lucideEyeOff' : 'lucideEye'" size="sm" />
                </button>
              </div>
            </div>
          </div>
          <div class="flex items-center gap-2">
            <hlm-checkbox id="remember-me" />
            <label hlmLabel for="remember-me" class="cursor-pointer text-sm font-normal">
              Remember me for 30 days
            </label>
          </div>
          <button hlmBtn class="w-full" type="button">Sign in</button>
          <div class="relative my-4">
            <div class="absolute inset-0 flex items-center">
              <span class="w-full border-t"></span>
            </div>
            <div class="relative flex justify-center text-xs uppercase">
              <span class="bg-card px-2 text-muted-foreground">Or continue with</span>
            </div>
          </div>
          <button hlmBtn variant="outline" class="w-full" type="button">
            <svg class="mr-2 h-4 w-4" viewBox="0 0 23 23">
              <path fill="#f35325" d="M1 1h10v10H1z"/>
              <path fill="#81bc06" d="M12 1h10v10H12z"/>
              <path fill="#05a6f0" d="M1 12h10v10H1z"/>
              <path fill="#ffba08" d="M12 12h10v10H12z"/>
            </svg>
            Continue with Microsoft 365
          </button>
        </form>
        <div hlmCardFooter class="justify-center">
          <p class="text-sm text-muted-foreground">
            Don't have an account?
            <a href="#" class="text-primary hover:underline">Sign up</a>
          </p>
        </div>
      </section>
    </div>
  \`,
})
export class AuthLoginBlockComponent {
  showPassword = signal(false);
  loginForm = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required]),
  });
}`;

export const authRegisterSource = `import { Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideMail, lucideLock, lucideEye, lucideEyeOff, lucideUser, lucideCheck, lucideX } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmLabelImports } from '@spartan-ng/helm/label';
import { HlmCardImports } from '@spartan-ng/helm/card';
import { HlmCheckboxImports } from '@spartan-ng/helm/checkbox';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmInputGroupImports } from '@spartan-ng/helm/input-group';

@Component({
  selector: 'app-auth-register-block',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    NgIcon,
    HlmIcon,
    HlmButtonImports,
    HlmInputImports,
    HlmLabelImports,
    HlmCardImports,
    HlmCheckboxImports,
    HlmInputGroupImports,
  ],
  viewProviders: [provideIcons({ lucideMail, lucideLock, lucideEye, lucideEyeOff, lucideUser, lucideCheck, lucideX })],
  template: \`
    <div class="flex h-full items-center justify-center bg-gradient-to-br from-background to-muted/50 overflow-auto py-8">
      <section hlmCard class="w-full max-w-md shadow-lg">
        <div hlmCardHeader class="text-center">
          <h2 hlmCardTitle class="text-2xl">Create an account</h2>
          <p hlmCardDescription>Enter your details to get started</p>
        </div>
        <form [formGroup]="registerForm" hlmCardContent class="space-y-4">
          <div class="space-y-2">
            <label hlmLabel for="register-name">Full Name</label>
            <div hlmInputGroup>
              <div hlmInputGroupAddon>
                <ng-icon hlm name="lucideUser" size="sm" />
              </div>
              <input hlmInputGroupInput id="register-name" type="text" formControlName="name" placeholder="John Doe" />
            </div>
          </div>
          <div class="space-y-2">
            <label hlmLabel for="register-email">Email</label>
            <div hlmInputGroup>
              <div hlmInputGroupAddon>
                <ng-icon hlm name="lucideMail" size="sm" />
              </div>
              <input hlmInputGroupInput id="register-email" type="email" formControlName="email" placeholder="name@example.com" />
            </div>
          </div>
          <div class="space-y-2">
            <label hlmLabel for="register-password">Password</label>
            <div hlmInputGroup>
              <div hlmInputGroupAddon>
                <ng-icon hlm name="lucideLock" size="sm" />
              </div>
              <input
                hlmInputGroupInput
                id="register-password"
                [type]="showPassword() ? 'text' : 'password'"
                formControlName="password"
                placeholder="Create a password"
              />
              <div hlmInputGroupAddon align="inline-end">
                <button type="button" hlmInputGroupButton variant="ghost" size="icon-sm" (click)="showPassword.set(!showPassword())">
                  <ng-icon hlm [name]="showPassword() ? 'lucideEyeOff' : 'lucideEye'" size="sm" />
                </button>
              </div>
            </div>
            @if (registerForm.get('password')?.value) {
              <div class="space-y-2">
                <div class="flex gap-1">
                  @for (i of [0, 1, 2, 3]; track i) {
                    <div class="h-1 flex-1 rounded-full transition-colors" [class]="i < passwordStrength() ? strengthColors[passwordStrength() - 1] : 'bg-muted'"></div>
                  }
                </div>
                <ul class="space-y-1 text-xs">
                  <li class="flex items-center gap-1" [class.text-green-600]="hasMinLength()" [class.text-muted-foreground]="!hasMinLength()">
                    <ng-icon hlm [name]="hasMinLength() ? 'lucideCheck' : 'lucideX'" size="xs" /> At least 8 characters
                  </li>
                  <li class="flex items-center gap-1" [class.text-green-600]="hasUppercase()" [class.text-muted-foreground]="!hasUppercase()">
                    <ng-icon hlm [name]="hasUppercase() ? 'lucideCheck' : 'lucideX'" size="xs" /> One uppercase letter
                  </li>
                  <li class="flex items-center gap-1" [class.text-green-600]="hasNumber()" [class.text-muted-foreground]="!hasNumber()">
                    <ng-icon hlm [name]="hasNumber() ? 'lucideCheck' : 'lucideX'" size="xs" /> One number
                  </li>
                </ul>
              </div>
            }
          </div>
          <div class="flex items-start gap-2">
            <hlm-checkbox id="accept-terms" class="mt-0.5" />
            <label hlmLabel for="accept-terms" class="cursor-pointer text-sm font-normal leading-relaxed">
              I agree to the <a href="#" class="text-primary hover:underline">Terms</a> and <a href="#" class="text-primary hover:underline">Privacy Policy</a>
            </label>
          </div>
          <button hlmBtn class="w-full" type="button">Create account</button>
          <div class="relative my-4">
            <div class="absolute inset-0 flex items-center"><span class="w-full border-t"></span></div>
            <div class="relative flex justify-center text-xs uppercase"><span class="bg-card px-2 text-muted-foreground">Or continue with</span></div>
          </div>
          <button hlmBtn variant="outline" class="w-full" type="button">
            <svg class="mr-2 h-4 w-4" viewBox="0 0 23 23"><path fill="#f35325" d="M1 1h10v10H1z"/><path fill="#81bc06" d="M12 1h10v10H12z"/><path fill="#05a6f0" d="M1 12h10v10H1z"/><path fill="#ffba08" d="M12 12h10v10H12z"/></svg>
            Continue with Microsoft 365
          </button>
        </form>
        <div hlmCardFooter class="justify-center">
          <p class="text-sm text-muted-foreground">Already have an account? <a href="#" class="text-primary hover:underline">Sign in</a></p>
        </div>
      </section>
    </div>
  \`,
})
export class AuthRegisterBlockComponent {
  showPassword = signal(false);
  strengthColors = ['bg-red-500', 'bg-orange-500', 'bg-yellow-500', 'bg-green-500'];
  registerForm = new FormGroup({
    name: new FormControl('', [Validators.required]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(8)]),
  });
  get password(): string { return this.registerForm.get('password')?.value || ''; }
  hasMinLength(): boolean { return this.password.length >= 8; }
  hasUppercase(): boolean { return /[A-Z]/.test(this.password); }
  hasNumber(): boolean { return /[0-9]/.test(this.password); }
  passwordStrength(): number {
    let s = 0;
    if (this.hasMinLength()) s++;
    if (this.hasUppercase()) s++;
    if (this.hasNumber()) s++;
    if (/[!@#$%^&*]/.test(this.password)) s++;
    return s;
  }
}`;

export const authForgotPasswordSource = `import { Component } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideMail, lucideArrowLeft } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmLabelImports } from '@spartan-ng/helm/label';
import { HlmCardImports } from '@spartan-ng/helm/card';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmInputGroupImports } from '@spartan-ng/helm/input-group';

@Component({
  selector: 'app-auth-forgot-password-block',
  standalone: true,
  imports: [ReactiveFormsModule, NgIcon, HlmIcon, HlmButtonImports, HlmInputImports, HlmLabelImports, HlmCardImports, HlmInputGroupImports],
  viewProviders: [provideIcons({ lucideMail, lucideArrowLeft })],
  template: \`
    <div class="flex h-full items-center justify-center bg-gradient-to-br from-background to-muted/50">
      <section hlmCard class="w-full max-w-md shadow-lg">
        <div hlmCardHeader class="text-center">
          <h2 hlmCardTitle class="text-2xl">Forgot password?</h2>
          <p hlmCardDescription>No worries, we'll send you reset instructions</p>
        </div>
        <form [formGroup]="form" hlmCardContent class="space-y-4">
          <div class="space-y-2">
            <label hlmLabel for="forgot-email">Email</label>
            <div hlmInputGroup>
              <div hlmInputGroupAddon><ng-icon hlm name="lucideMail" size="sm" /></div>
              <input hlmInputGroupInput id="forgot-email" type="email" formControlName="email" placeholder="name@example.com" />
            </div>
          </div>
          <button hlmBtn class="w-full" type="button">Reset password</button>
          <div class="relative my-4">
            <div class="absolute inset-0 flex items-center"><span class="w-full border-t"></span></div>
            <div class="relative flex justify-center text-xs uppercase"><span class="bg-card px-2 text-muted-foreground">Or continue with</span></div>
          </div>
          <button hlmBtn variant="outline" class="w-full" type="button">
            <svg class="mr-2 h-4 w-4" viewBox="0 0 23 23"><path fill="#f35325" d="M1 1h10v10H1z"/><path fill="#81bc06" d="M12 1h10v10H12z"/><path fill="#05a6f0" d="M1 12h10v10H1z"/><path fill="#ffba08" d="M12 12h10v10H12z"/></svg>
            Continue with Microsoft 365
          </button>
        </form>
        <div hlmCardFooter class="justify-center">
          <a href="#" class="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">
            <ng-icon hlm name="lucideArrowLeft" size="sm" /> Back to login
          </a>
        </div>
      </section>
    </div>
  \`,
})
export class AuthForgotPasswordBlockComponent {
  form = new FormGroup({ email: new FormControl('', [Validators.required, Validators.email]) });
}`;

export const shellSidebarSource = `import { Component, signal } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideUser, lucideSun, lucideMoon } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmIcon } from '@spartan-ng/helm/icon';

@Component({
  selector: 'app-shell-sidebar-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports],
  viewProviders: [provideIcons({ lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideUser, lucideSun, lucideMoon })],
  template: \`
    <div class="flex h-full">
      <aside class="w-64 border-r bg-card flex flex-col">
        <div class="p-4 border-b">
          <div class="flex items-center gap-2">
            <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <span class="text-sm font-bold">A</span>
            </div>
            <span class="font-semibold">Acme Inc</span>
          </div>
        </div>
        <nav class="flex-1 p-4 space-y-1">
          @for (item of navItems; track item.label) {
            <a href="#" class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-colors"
               [class]="item.active ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'">
              <ng-icon hlm [name]="item.icon" size="sm" />
              {{ item.label }}
            </a>
          }
        </nav>
        <div class="p-4 border-t">
          <div class="flex items-center gap-3">
            <div class="flex h-8 w-8 items-center justify-center rounded-full bg-muted">
              <ng-icon hlm name="lucideUser" size="sm" />
            </div>
            <div class="flex-1 min-w-0">
              <p class="text-sm font-medium truncate">John Doe</p>
              <p class="text-xs text-muted-foreground truncate">john&#64;example.com</p>
            </div>
          </div>
        </div>
      </aside>
      <div class="flex-1 flex flex-col">
        <header class="h-14 border-b px-6 flex items-center justify-between">
          <h1 class="text-lg font-semibold">Dashboard</h1>
          <div class="flex items-center gap-2">
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideBell" size="sm" /></button>
            <button hlmBtn variant="ghost" size="icon" (click)="toggleTheme()">
              <ng-icon hlm [name]="isDark() ? 'lucideSun' : 'lucideMoon'" size="sm" />
            </button>
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideSettings" size="sm" /></button>
          </div>
        </header>
        <main class="flex-1 p-6 bg-muted/30 overflow-auto">
          <div class="grid gap-4 md:grid-cols-3">
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Total Users</p><p class="text-2xl font-bold">1,234</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Revenue</p><p class="text-2xl font-bold">$12,345</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Active Projects</p><p class="text-2xl font-bold">23</p></div>
          </div>
        </main>
      </div>
    </div>
  \`,
})
export class ShellSidebarBlockComponent {
  isDark = signal(typeof document !== 'undefined' && document.documentElement.classList.contains('dark'));

  toggleTheme() {
    document.documentElement.classList.toggle('dark');
    this.isDark.set(document.documentElement.classList.contains('dark'));
  }

  navItems = [
    { icon: 'lucideHome', label: 'Dashboard', active: true },
    { icon: 'lucideUsers', label: 'Users', active: false },
    { icon: 'lucideFileText', label: 'Documents', active: false },
    { icon: 'lucideBarChart3', label: 'Analytics', active: false },
    { icon: 'lucideSettings', label: 'Settings', active: false },
  ];
}`;

export const shellTopnavSource = `import { Component, signal } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBell, lucideSearch, lucideChevronDown, lucideLogOut, lucideUser, lucideSettings, lucideSun, lucideMoon } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmDropdownMenuImports } from '@spartan-ng/helm/dropdown-menu';

@Component({
  selector: 'app-shell-topnav-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports, HlmInputImports, HlmDropdownMenuImports],
  viewProviders: [provideIcons({ lucideBell, lucideSearch, lucideChevronDown, lucideLogOut, lucideUser, lucideSettings, lucideSun, lucideMoon })],
  template: \`
    <div class="flex flex-col h-full">
      <header class="border-b bg-card">
        <div class="flex h-14 items-center px-6 gap-6">
          <div class="flex items-center gap-2">
            <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <span class="text-sm font-bold">A</span>
            </div>
            <span class="font-semibold">Acme Inc</span>
          </div>
          <nav class="flex items-center gap-1">
            @for (item of navItems; track item.label) {
              <a href="#" class="px-3 py-1.5 text-sm font-medium rounded-md transition-colors"
                 [class]="item.active ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'">
                {{ item.label }}
              </a>
            }
          </nav>
          <div class="flex-1"></div>
          <div class="flex items-center gap-2">
            <div class="relative">
              <ng-icon hlm name="lucideSearch" size="sm" class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
              <input hlmInput type="search" placeholder="Search..." class="pl-9 w-64" />
            </div>
            <button hlmBtn variant="ghost" size="icon" (click)="toggleTheme()">
              <ng-icon hlm [name]="isDark() ? 'lucideSun' : 'lucideMoon'" size="sm" />
            </button>
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideBell" size="sm" /></button>
            <button hlmBtn variant="ghost" size="sm" [hlmDropdownMenuTrigger]="userMenu">
              <div class="flex h-6 w-6 items-center justify-center rounded-full bg-muted"><ng-icon hlm name="lucideUser" size="xs" /></div>
              <ng-icon hlm name="lucideChevronDown" size="xs" />
            </button>
            <ng-template #userMenu>
              <hlm-dropdown-menu class="w-48">
                <hlm-dropdown-menu-label>My Account</hlm-dropdown-menu-label>
                <hlm-dropdown-menu-separator />
                <button hlmDropdownMenuItem><ng-icon hlm name="lucideUser" class="mr-2" size="sm" />Profile</button>
                <button hlmDropdownMenuItem><ng-icon hlm name="lucideSettings" class="mr-2" size="sm" />Settings</button>
                <hlm-dropdown-menu-separator />
                <button hlmDropdownMenuItem><ng-icon hlm name="lucideLogOut" class="mr-2" size="sm" />Log out</button>
              </hlm-dropdown-menu>
            </ng-template>
          </div>
        </div>
      </header>
      <main class="flex-1 p-6 bg-muted/30 overflow-auto">
        <div class="max-w-5xl mx-auto space-y-6">
          <div><h1 class="text-2xl font-bold">Welcome back, John</h1><p class="text-muted-foreground">Here's what's happening with your projects today.</p></div>
          <div class="grid gap-4 md:grid-cols-4">
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Total Users</p><p class="text-2xl font-bold">1,234</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Revenue</p><p class="text-2xl font-bold">$12,345</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Active Projects</p><p class="text-2xl font-bold">23</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Pending Tasks</p><p class="text-2xl font-bold">8</p></div>
          </div>
        </div>
      </main>
    </div>
  \`,
})
export class ShellTopnavBlockComponent {
  isDark = signal(typeof document !== 'undefined' && document.documentElement.classList.contains('dark'));

  toggleTheme() {
    document.documentElement.classList.toggle('dark');
    this.isDark.set(document.documentElement.classList.contains('dark'));
  }

  navItems = [
    { label: 'Dashboard', active: true },
    { label: 'Projects', active: false },
    { label: 'Team', active: false },
    { label: 'Reports', active: false },
  ];
}`;

export const shellCollapsibleSource = `import { Component, signal } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideMenu, lucideSun, lucideMoon } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmIcon } from '@spartan-ng/helm/icon';

@Component({
  selector: 'app-shell-collapsible-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports],
  viewProviders: [provideIcons({ lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideMenu, lucideSun, lucideMoon })],
  template: \`
    <div class="flex h-full">
      <aside class="border-r bg-card flex flex-col transition-all duration-300" [class]="collapsed() ? 'w-16' : 'w-64'">
        <div class="p-4 border-b flex items-center" [class.justify-center]="collapsed()">
          @if (!collapsed()) {
            <div class="flex items-center gap-2">
              <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><span class="text-sm font-bold">A</span></div>
              <span class="font-semibold">Acme Inc</span>
            </div>
          } @else {
            <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><span class="text-sm font-bold">A</span></div>
          }
        </div>
        <nav class="flex-1 p-2 space-y-1">
          @for (item of navItems; track item.label) {
            <a href="#" class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-colors"
               [class]="item.active ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'"
               [class.justify-center]="collapsed()">
              <ng-icon hlm [name]="item.icon" size="sm" />
              @if (!collapsed()) { <span>{{ item.label }}</span> }
            </a>
          }
        </nav>
        <div class="p-2 border-t">
          <button hlmBtn variant="ghost" size="sm" class="w-full" [class.justify-center]="collapsed()" (click)="collapsed.set(!collapsed())">
            <ng-icon hlm name="lucideMenu" size="sm" />
            @if (!collapsed()) { <span class="ml-2">Collapse</span> }
          </button>
        </div>
      </aside>
      <div class="flex-1 flex flex-col">
        <header class="h-14 border-b px-6 flex items-center justify-between">
          <h1 class="text-lg font-semibold">Dashboard</h1>
          <div class="flex items-center gap-2">
            <button hlmBtn variant="ghost" size="icon" (click)="toggleTheme()">
              <ng-icon hlm [name]="isDark() ? 'lucideSun' : 'lucideMoon'" size="sm" />
            </button>
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideBell" size="sm" /></button>
          </div>
        </header>
        <main class="flex-1 p-6 bg-muted/30 overflow-auto">
          <p class="text-muted-foreground mb-4">Click "Collapse" in the sidebar to toggle between expanded and collapsed states.</p>
          <div class="grid gap-4 md:grid-cols-3">
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Total Users</p><p class="text-2xl font-bold">1,234</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Revenue</p><p class="text-2xl font-bold">$12,345</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Active Projects</p><p class="text-2xl font-bold">23</p></div>
          </div>
        </main>
      </div>
    </div>
  \`,
})
export class ShellCollapsibleBlockComponent {
  collapsed = signal(false);
  isDark = signal(typeof document !== 'undefined' && document.documentElement.classList.contains('dark'));

  toggleTheme() {
    document.documentElement.classList.toggle('dark');
    this.isDark.set(document.documentElement.classList.contains('dark'));
  }
  navItems = [
    { icon: 'lucideHome', label: 'Dashboard', active: true },
    { icon: 'lucideUsers', label: 'Users', active: false },
    { icon: 'lucideFileText', label: 'Documents', active: false },
    { icon: 'lucideBarChart3', label: 'Analytics', active: false },
    { icon: 'lucideSettings', label: 'Settings', active: false },
  ];
}`;

export const shellSidebarFooterSource = `import { Component, signal } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideUser, lucideSun, lucideMoon } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmIcon } from '@spartan-ng/helm/icon';

@Component({
  selector: 'app-shell-sidebar-footer-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports],
  viewProviders: [provideIcons({ lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideUser, lucideSun, lucideMoon })],
  template: \`
    <div class="flex h-full">
      <aside class="w-64 border-r bg-card flex flex-col">
        <div class="p-4 border-b">
          <div class="flex items-center gap-2">
            <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <span class="text-sm font-bold">A</span>
            </div>
            <span class="font-semibold">Acme Inc</span>
          </div>
        </div>
        <nav class="flex-1 p-4 space-y-1">
          @for (item of navItems; track item.label) {
            <a href="#" class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-colors"
               [class]="item.active ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'">
              <ng-icon hlm [name]="item.icon" size="sm" />
              {{ item.label }}
            </a>
          }
        </nav>
        <div class="p-4 border-t">
          <div class="flex items-center gap-3">
            <div class="flex h-8 w-8 items-center justify-center rounded-full bg-muted">
              <ng-icon hlm name="lucideUser" size="sm" />
            </div>
            <div class="flex-1 min-w-0">
              <p class="text-sm font-medium truncate">John Doe</p>
              <p class="text-xs text-muted-foreground truncate">john&#64;example.com</p>
            </div>
          </div>
        </div>
      </aside>
      <div class="flex-1 flex flex-col">
        <header class="h-14 border-b px-6 flex items-center justify-between">
          <h1 class="text-lg font-semibold">Dashboard</h1>
          <div class="flex items-center gap-2">
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideBell" size="sm" /></button>
            <button hlmBtn variant="ghost" size="icon" (click)="toggleTheme()">
              <ng-icon hlm [name]="isDark() ? 'lucideSun' : 'lucideMoon'" size="sm" />
            </button>
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideSettings" size="sm" /></button>
          </div>
        </header>
        <main class="flex-1 p-6 bg-muted/30 overflow-auto">
          <div class="grid gap-4 md:grid-cols-3">
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Total Users</p><p class="text-2xl font-bold">1,234</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Revenue</p><p class="text-2xl font-bold">$12,345</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Active Projects</p><p class="text-2xl font-bold">23</p></div>
          </div>
        </main>
        <footer class="border-t bg-card px-6 py-4">
          <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <p class="text-sm text-muted-foreground">© {{ currentYear }} Acme Inc. All rights reserved.</p>
            <nav class="flex items-center gap-4">
              @for (link of footerLinks; track link.label) {
                <a href="#" class="text-sm text-muted-foreground hover:text-foreground transition-colors">{{ link.label }}</a>
              }
            </nav>
          </div>
        </footer>
      </div>
    </div>
  \`,
})
export class ShellSidebarFooterBlockComponent {
  currentYear = new Date().getFullYear();
  isDark = signal(typeof document !== 'undefined' && document.documentElement.classList.contains('dark'));

  toggleTheme() {
    document.documentElement.classList.toggle('dark');
    this.isDark.set(document.documentElement.classList.contains('dark'));
  }

  navItems = [
    { icon: 'lucideHome', label: 'Dashboard', active: true },
    { icon: 'lucideUsers', label: 'Users', active: false },
    { icon: 'lucideFileText', label: 'Documents', active: false },
    { icon: 'lucideBarChart3', label: 'Analytics', active: false },
    { icon: 'lucideSettings', label: 'Settings', active: false },
  ];

  footerLinks = [
    { label: 'Privacy Policy' },
    { label: 'Terms of Service' },
    { label: 'Help Center' },
  ];
}`;

export const shellTopnavFooterSource = `import { Component, signal } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBell, lucideSearch, lucideChevronDown, lucideLogOut, lucideUser, lucideSettings, lucideSun, lucideMoon } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmDropdownMenuImports } from '@spartan-ng/helm/dropdown-menu';

@Component({
  selector: 'app-shell-topnav-footer-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports, HlmInputImports, HlmDropdownMenuImports],
  viewProviders: [provideIcons({ lucideBell, lucideSearch, lucideChevronDown, lucideLogOut, lucideUser, lucideSettings, lucideSun, lucideMoon })],
  template: \`
    <div class="flex flex-col h-full">
      <header class="border-b bg-card">
        <div class="flex h-14 items-center px-6 gap-6">
          <div class="flex items-center gap-2">
            <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <span class="text-sm font-bold">A</span>
            </div>
            <span class="font-semibold">Acme Inc</span>
          </div>
          <nav class="flex items-center gap-1">
            @for (item of navItems; track item.label) {
              <a href="#" class="px-3 py-1.5 text-sm font-medium rounded-md transition-colors"
                 [class]="item.active ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'">
                {{ item.label }}
              </a>
            }
          </nav>
          <div class="flex-1"></div>
          <div class="flex items-center gap-2">
            <div class="relative">
              <ng-icon hlm name="lucideSearch" size="sm" class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
              <input hlmInput type="search" placeholder="Search..." class="pl-9 w-64" />
            </div>
            <button hlmBtn variant="ghost" size="icon" (click)="toggleTheme()">
              <ng-icon hlm [name]="isDark() ? 'lucideSun' : 'lucideMoon'" size="sm" />
            </button>
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideBell" size="sm" /></button>
            <button hlmBtn variant="ghost" size="sm" [hlmDropdownMenuTrigger]="userMenu">
              <div class="flex h-6 w-6 items-center justify-center rounded-full bg-muted"><ng-icon hlm name="lucideUser" size="xs" /></div>
              <ng-icon hlm name="lucideChevronDown" size="xs" />
            </button>
            <ng-template #userMenu>
              <hlm-dropdown-menu class="w-48">
                <hlm-dropdown-menu-label>My Account</hlm-dropdown-menu-label>
                <hlm-dropdown-menu-separator />
                <button hlmDropdownMenuItem><ng-icon hlm name="lucideUser" class="mr-2" size="sm" />Profile</button>
                <button hlmDropdownMenuItem><ng-icon hlm name="lucideSettings" class="mr-2" size="sm" />Settings</button>
                <hlm-dropdown-menu-separator />
                <button hlmDropdownMenuItem><ng-icon hlm name="lucideLogOut" class="mr-2" size="sm" />Log out</button>
              </hlm-dropdown-menu>
            </ng-template>
          </div>
        </div>
      </header>
      <main class="flex-1 p-6 bg-muted/30 overflow-auto">
        <div class="max-w-5xl mx-auto space-y-6">
          <div><h1 class="text-2xl font-bold">Welcome back, John</h1><p class="text-muted-foreground">Here's what's happening with your projects today.</p></div>
          <div class="grid gap-4 md:grid-cols-4">
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Total Users</p><p class="text-2xl font-bold">1,234</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Revenue</p><p class="text-2xl font-bold">$12,345</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Active Projects</p><p class="text-2xl font-bold">23</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Pending Tasks</p><p class="text-2xl font-bold">8</p></div>
          </div>
        </div>
      </main>
      <footer class="border-t bg-card px-6 py-4">
        <div class="max-w-5xl mx-auto flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <p class="text-sm text-muted-foreground">© {{ currentYear }} Acme Inc. All rights reserved.</p>
          <nav class="flex items-center gap-4">
            @for (link of footerLinks; track link.label) {
              <a href="#" class="text-sm text-muted-foreground hover:text-foreground transition-colors">{{ link.label }}</a>
            }
          </nav>
        </div>
      </footer>
    </div>
  \`,
})
export class ShellTopnavFooterBlockComponent {
  currentYear = new Date().getFullYear();
  isDark = signal(typeof document !== 'undefined' && document.documentElement.classList.contains('dark'));

  toggleTheme() {
    document.documentElement.classList.toggle('dark');
    this.isDark.set(document.documentElement.classList.contains('dark'));
  }

  navItems = [
    { label: 'Dashboard', active: true },
    { label: 'Projects', active: false },
    { label: 'Team', active: false },
    { label: 'Reports', active: false },
  ];

  footerLinks = [
    { label: 'Privacy Policy' },
    { label: 'Terms of Service' },
    { label: 'Help Center' },
  ];
}`;

export const shellCollapsibleFooterSource = `import { Component, signal } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideMenu, lucideSun, lucideMoon } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmIcon } from '@spartan-ng/helm/icon';

@Component({
  selector: 'app-shell-collapsible-footer-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports],
  viewProviders: [provideIcons({ lucideHome, lucideUsers, lucideSettings, lucideFileText, lucideBarChart3, lucideBell, lucideMenu, lucideSun, lucideMoon })],
  template: \`
    <div class="flex h-full">
      <aside class="border-r bg-card flex flex-col transition-all duration-300" [class]="collapsed() ? 'w-16' : 'w-64'">
        <div class="p-4 border-b flex items-center" [class.justify-center]="collapsed()">
          @if (!collapsed()) {
            <div class="flex items-center gap-2">
              <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><span class="text-sm font-bold">A</span></div>
              <span class="font-semibold">Acme Inc</span>
            </div>
          } @else {
            <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><span class="text-sm font-bold">A</span></div>
          }
        </div>
        <nav class="flex-1 p-2 space-y-1">
          @for (item of navItems; track item.label) {
            <a href="#" class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-colors"
               [class]="item.active ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'"
               [class.justify-center]="collapsed()">
              <ng-icon hlm [name]="item.icon" size="sm" />
              @if (!collapsed()) { <span>{{ item.label }}</span> }
            </a>
          }
        </nav>
        <div class="p-2 border-t">
          <button hlmBtn variant="ghost" size="sm" class="w-full" [class.justify-center]="collapsed()" (click)="collapsed.set(!collapsed())">
            <ng-icon hlm name="lucideMenu" size="sm" />
            @if (!collapsed()) { <span class="ml-2">Collapse</span> }
          </button>
        </div>
      </aside>
      <div class="flex-1 flex flex-col">
        <header class="h-14 border-b px-6 flex items-center justify-between">
          <h1 class="text-lg font-semibold">Dashboard</h1>
          <div class="flex items-center gap-2">
            <button hlmBtn variant="ghost" size="icon" (click)="toggleTheme()">
              <ng-icon hlm [name]="isDark() ? 'lucideSun' : 'lucideMoon'" size="sm" />
            </button>
            <button hlmBtn variant="ghost" size="icon"><ng-icon hlm name="lucideBell" size="sm" /></button>
          </div>
        </header>
        <main class="flex-1 p-6 bg-muted/30 overflow-auto">
          <p class="text-muted-foreground mb-4">Click "Collapse" in the sidebar to toggle between expanded and collapsed states.</p>
          <div class="grid gap-4 md:grid-cols-3">
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Total Users</p><p class="text-2xl font-bold">1,234</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Revenue</p><p class="text-2xl font-bold">$12,345</p></div>
            <div class="rounded-lg border bg-card p-4"><p class="text-sm text-muted-foreground">Active Projects</p><p class="text-2xl font-bold">23</p></div>
          </div>
        </main>
        <footer class="border-t bg-card px-6 py-4">
          <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <p class="text-sm text-muted-foreground">© {{ currentYear }} Acme Inc. All rights reserved.</p>
            <nav class="flex items-center gap-4">
              @for (link of footerLinks; track link.label) {
                <a href="#" class="text-sm text-muted-foreground hover:text-foreground transition-colors">{{ link.label }}</a>
              }
            </nav>
          </div>
        </footer>
      </div>
    </div>
  \`,
})
export class ShellCollapsibleFooterBlockComponent {
  collapsed = signal(false);
  currentYear = new Date().getFullYear();
  isDark = signal(typeof document !== 'undefined' && document.documentElement.classList.contains('dark'));

  toggleTheme() {
    document.documentElement.classList.toggle('dark');
    this.isDark.set(document.documentElement.classList.contains('dark'));
  }

  navItems = [
    { icon: 'lucideHome', label: 'Dashboard', active: true },
    { icon: 'lucideUsers', label: 'Users', active: false },
    { icon: 'lucideFileText', label: 'Documents', active: false },
    { icon: 'lucideBarChart3', label: 'Analytics', active: false },
    { icon: 'lucideSettings', label: 'Settings', active: false },
  ];

  footerLinks = [
    { label: 'Privacy Policy' },
    { label: 'Terms of Service' },
    { label: 'Help Center' },
  ];
}`;

export const settingsProfileSource = `import { Component } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideUser } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmLabelImports } from '@spartan-ng/helm/label';
import { HlmCardImports } from '@spartan-ng/helm/card';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmSeparatorImports } from '@spartan-ng/helm/separator';

@Component({
  selector: 'app-settings-profile-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports, HlmInputImports, HlmLabelImports, HlmCardImports, HlmSeparatorImports],
  viewProviders: [provideIcons({ lucideUser })],
  template: \`
    <div class="h-full overflow-auto bg-muted/30 p-6">
      <div class="max-w-2xl mx-auto">
        <section hlmCard>
          <div hlmCardHeader>
            <div class="flex items-center gap-3">
              <ng-icon hlm name="lucideUser" size="sm" class="text-muted-foreground" />
              <div>
                <h3 hlmCardTitle>Profile</h3>
                <p hlmCardDescription>Manage your public profile information</p>
              </div>
            </div>
          </div>
          <div hlmCardContent class="space-y-6">
            <div class="flex items-center gap-4">
              <div class="flex h-20 w-20 items-center justify-center rounded-full bg-muted">
                <ng-icon hlm name="lucideUser" size="lg" />
              </div>
              <div class="space-y-2">
                <button hlmBtn variant="outline" size="sm">Change avatar</button>
                <p class="text-xs text-muted-foreground">JPG, GIF or PNG. Max size 2MB.</p>
              </div>
            </div>
            <hlm-separator />
            <div class="grid gap-4 sm:grid-cols-2">
              <div class="space-y-2">
                <label hlmLabel for="firstname">First name</label>
                <input hlmInput id="firstname" value="John" />
              </div>
              <div class="space-y-2">
                <label hlmLabel for="lastname">Last name</label>
                <input hlmInput id="lastname" value="Doe" />
              </div>
            </div>
            <div class="space-y-2">
              <label hlmLabel for="email">Email</label>
              <input hlmInput id="email" type="email" value="john.doe@example.com" />
            </div>
            <div class="space-y-2">
              <label hlmLabel for="bio">Bio</label>
              <textarea hlmInput id="bio" rows="3" placeholder="Tell us about yourself..."></textarea>
            </div>
          </div>
          <div hlmCardFooter class="justify-end gap-2">
            <button hlmBtn variant="outline">Cancel</button>
            <button hlmBtn>Save changes</button>
          </div>
        </section>
      </div>
    </div>
  \`,
})
export class SettingsProfileBlockComponent {}`;

export const settingsNotificationsSource = `import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBell } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmCardImports } from '@spartan-ng/helm/card';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmLabelImports } from '@spartan-ng/helm/label';
import { HlmSwitchImports } from '@spartan-ng/helm/switch';
import { HlmSeparatorImports } from '@spartan-ng/helm/separator';

@Component({
  selector: 'app-settings-notifications-block',
  standalone: true,
  imports: [FormsModule, NgIcon, HlmIcon, HlmButtonImports, HlmCardImports, HlmLabelImports, HlmSwitchImports, HlmSeparatorImports],
  viewProviders: [provideIcons({ lucideBell })],
  template: \`
    <div class="h-full overflow-auto bg-muted/30 p-6">
      <div class="max-w-2xl mx-auto">
        <section hlmCard>
          <div hlmCardHeader>
            <div class="flex items-center gap-3">
              <ng-icon hlm name="lucideBell" size="sm" class="text-muted-foreground" />
              <div>
                <h3 hlmCardTitle>Notifications</h3>
                <p hlmCardDescription>Choose what notifications you receive</p>
              </div>
            </div>
          </div>
          <div hlmCardContent class="space-y-6">
            @for (group of notificationGroups; track group.title) {
              <div class="space-y-4">
                <h4 class="text-sm font-medium">{{ group.title }}</h4>
                @for (item of group.items; track item.label) {
                  <div class="flex items-center justify-between">
                    <div class="space-y-0.5">
                      <label hlmLabel class="text-sm font-normal">{{ item.label }}</label>
                      <p class="text-xs text-muted-foreground">{{ item.description }}</p>
                    </div>
                    <hlm-switch [(checked)]="item.enabled" />
                  </div>
                }
                @if (!$last) { <hlm-separator /> }
              </div>
            }
          </div>
          <div hlmCardFooter class="justify-end">
            <button hlmBtn>Save preferences</button>
          </div>
        </section>
      </div>
    </div>
  \`,
})
export class SettingsNotificationsBlockComponent {
  notificationGroups = [
    {
      title: 'Email Notifications',
      items: [
        { label: 'Marketing emails', description: 'Receive emails about new features and updates', enabled: true },
        { label: 'Security alerts', description: 'Get notified about security events', enabled: true },
        { label: 'Weekly digest', description: 'Weekly summary of your activity', enabled: false },
      ],
    },
    {
      title: 'Push Notifications',
      items: [
        { label: 'Direct messages', description: 'Notifications for new messages', enabled: true },
        { label: 'Mentions', description: 'When someone mentions you', enabled: true },
        { label: 'Comments', description: 'Replies to your posts', enabled: false },
      ],
    },
  ];
}`;

export const settingsSecuritySource = `import { Component } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideShield } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmLabelImports } from '@spartan-ng/helm/label';
import { HlmCardImports } from '@spartan-ng/helm/card';
import { HlmIcon } from '@spartan-ng/helm/icon';
import { HlmBadgeImports } from '@spartan-ng/helm/badge';
import { HlmSwitchImports } from '@spartan-ng/helm/switch';
import { HlmSeparatorImports } from '@spartan-ng/helm/separator';

@Component({
  selector: 'app-settings-security-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports, HlmInputImports, HlmLabelImports, HlmCardImports, HlmBadgeImports, HlmSwitchImports, HlmSeparatorImports],
  viewProviders: [provideIcons({ lucideShield })],
  template: \`
    <div class="h-full overflow-auto bg-muted/30 p-6">
      <div class="max-w-2xl mx-auto">
        <section hlmCard>
          <div hlmCardHeader>
            <div class="flex items-center gap-3">
              <ng-icon hlm name="lucideShield" size="sm" class="text-muted-foreground" />
              <div>
                <h3 hlmCardTitle>Security</h3>
                <p hlmCardDescription>Manage your account security settings</p>
              </div>
            </div>
          </div>
          <div hlmCardContent class="space-y-6">
            <div class="space-y-4">
              <h4 class="text-sm font-medium">Change Password</h4>
              <div class="space-y-4">
                <div class="space-y-2">
                  <label hlmLabel for="current-password">Current password</label>
                  <input hlmInput id="current-password" type="password" />
                </div>
                <div class="space-y-2">
                  <label hlmLabel for="new-password">New password</label>
                  <input hlmInput id="new-password" type="password" />
                </div>
                <div class="space-y-2">
                  <label hlmLabel for="confirm-password">Confirm new password</label>
                  <input hlmInput id="confirm-password" type="password" />
                </div>
              </div>
              <button hlmBtn>Update password</button>
            </div>
            <hlm-separator />
            <div class="space-y-4">
              <div class="flex items-center justify-between">
                <div class="space-y-0.5">
                  <h4 class="text-sm font-medium">Two-factor authentication</h4>
                  <p class="text-xs text-muted-foreground">Add an extra layer of security to your account</p>
                </div>
                <hlm-switch />
              </div>
            </div>
            <hlm-separator />
            <div class="space-y-4">
              <h4 class="text-sm font-medium">Active Sessions</h4>
              <div class="space-y-3">
                @for (session of sessions; track session.device) {
                  <div class="flex items-center justify-between p-3 rounded-lg border">
                    <div class="space-y-0.5">
                      <p class="text-sm font-medium">{{ session.device }}</p>
                      <p class="text-xs text-muted-foreground">{{ session.location }} · {{ session.time }}</p>
                    </div>
                    @if (session.current) {
                      <span hlmBadge variant="secondary">Current</span>
                    } @else {
                      <button hlmBtn variant="ghost" size="sm">Revoke</button>
                    }
                  </div>
                }
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  \`,
})
export class SettingsSecurityBlockComponent {
  sessions = [
    { device: 'Chrome on MacOS', location: 'San Francisco, CA', time: 'Active now', current: true },
    { device: 'Safari on iPhone', location: 'San Francisco, CA', time: '2 hours ago', current: false },
    { device: 'Firefox on Windows', location: 'New York, NY', time: '3 days ago', current: false },
  ];
}`;

export const settingsDangerSource = `import { Component } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideTrash2 } from '@ng-icons/lucide';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmCardImports } from '@spartan-ng/helm/card';
import { HlmIcon } from '@spartan-ng/helm/icon';

@Component({
  selector: 'app-settings-danger-block',
  standalone: true,
  imports: [NgIcon, HlmIcon, HlmButtonImports, HlmCardImports],
  viewProviders: [provideIcons({ lucideTrash2 })],
  template: \`
    <div class="h-full overflow-auto bg-muted/30 p-6">
      <div class="max-w-2xl mx-auto">
        <section hlmCard class="border-destructive/50">
          <div hlmCardHeader>
            <div class="flex items-center gap-3">
              <ng-icon hlm name="lucideTrash2" size="sm" class="text-destructive" />
              <div>
                <h3 hlmCardTitle class="text-destructive">Danger Zone</h3>
                <p hlmCardDescription>Irreversible and destructive actions</p>
              </div>
            </div>
          </div>
          <div hlmCardContent class="space-y-4">
            <div class="flex items-center justify-between p-4 rounded-lg border border-destructive/30 bg-destructive/5">
              <div class="space-y-0.5">
                <p class="text-sm font-medium">Delete Account</p>
                <p class="text-xs text-muted-foreground">Permanently delete your account and all data</p>
              </div>
              <button hlmBtn variant="destructive" size="sm">Delete Account</button>
            </div>
            <div class="flex items-center justify-between p-4 rounded-lg border border-destructive/30 bg-destructive/5">
              <div class="space-y-0.5">
                <p class="text-sm font-medium">Export Data</p>
                <p class="text-xs text-muted-foreground">Download all your data before deletion</p>
              </div>
              <button hlmBtn variant="outline" size="sm">Export</button>
            </div>
          </div>
        </section>
      </div>
    </div>
  \`,
})
export class SettingsDangerBlockComponent {}`;

// Map of blocks IDs to their source code
export const blockSourceMap: Record<string, string> = {
  'auth-login': authLoginSource,
  'auth-register': authRegisterSource,
  'auth-forgot-password': authForgotPasswordSource,
  'shell-sidebar': shellSidebarSource,
  'shell-topnav': shellTopnavSource,
  'shell-collapsible': shellCollapsibleSource,
  'shell-sidebar-footer': shellSidebarFooterSource,
  'shell-topnav-footer': shellTopnavFooterSource,
  'shell-collapsible-footer': shellCollapsibleFooterSource,
  'settings-profile': settingsProfileSource,
  'settings-notifications': settingsNotificationsSource,
  'settings-security': settingsSecuritySource,
  'settings-danger': settingsDangerSource,
};
